[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:moto_s3]
command=moto_server -H 0.0.0.0 -p 5000
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:fastapi_predict]
command=uvicorn mlops.server:app --host 0.0.0.0 --port 8000 --reload
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
