# %% [markdown]
# # 📊 Live MLOps Tracking Dashboard
#
# This dashboard aggregates and presents the tracking data generated by running the tutorial pipeline modules. It queries **MLflow** for experiment history and model registrations, and inspects **DVC** for data version status.
#
# Because `execute: true` is configured in `mkdocs.yml`, the metrics and logs shown here are automatically re-evaluated and refreshed whenever the tutorials are compiled.

# %%
import os
import mlflow
import pandas as pd
from IPython.display import display, HTML

# Display current tracking URI configurations
tracking_uri = mlflow.get_tracking_uri()
print(f"📁 MLflow Tracking URI: {tracking_uri}")
try:
    resolved_path = os.path.abspath(tracking_uri.replace('file://', ''))
    print(f"📂 Resolved Absolute Path: {resolved_path}")
except Exception:
    pass

# %% [markdown]
# ## 🔬 MLflow Runs Summary
#
# List of all active tracking experiments and their recorded metrics:

# %%
try:
    experiments = mlflow.search_experiments()
    if not experiments:
        print("ℹ️ No MLflow experiments found. Run some tutorial scripts first!")
    else:
        runs_df = mlflow.search_runs()
        if runs_df.empty:
            print("ℹ️ MLflow tracking directory exists, but no runs have been logged yet.")
        else:
            # Format Date/Time
            if 'start_time' in runs_df.columns:
                runs_df['start_time'] = pd.to_datetime(runs_df['start_time']).dt.strftime('%Y-%m-%d %H:%M:%S')
            
            # Map experiment names
            exp_mapping = {exp.experiment_id: exp.name for exp in experiments}
            runs_df['experiment_name'] = runs_df['experiment_id'].map(exp_mapping)
            
            # Identify parameter and metric columns
            param_cols = [col for col in runs_df.columns if col.startswith('params.')]
            metric_cols = [col for col in runs_df.columns if col.startswith('metrics.')]
            
            # Select columns to display
            all_display_cols = ['experiment_name', 'run_id', 'status', 'start_time'] + param_cols + metric_cols
            all_display_cols = [c for c in all_display_cols if c in runs_df.columns]
            
            display_df = runs_df[all_display_cols].copy()
            
            # Strip column prefixes
            rename_dict = {}
            for col in display_df.columns:
                if col.startswith('params.'):
                    rename_dict[col] = f"🔧 {col.replace('params.', '')}"
                elif col.startswith('metrics.'):
                    rename_dict[col] = f"📈 {col.replace('metrics.', '')}"
                elif col == 'experiment_name':
                    rename_dict[col] = 'Experiment'
                elif col == 'run_id':
                    rename_dict[col] = 'Run ID'
                elif col == 'status':
                    rename_dict[col] = 'Status'
                elif col == 'start_time':
                    rename_dict[col] = 'Date/Time'
            
            display_df.rename(columns=rename_dict, inplace=True)
            display(HTML(display_df.to_html(classes='dataframe', index=False)))
except Exception as e:
    print(f"⚠️ Error loading MLflow runs: {e}")

# %% [markdown]
# ## 📦 Model Registry
#
# The Model Registry stores versions of models ready for deployment:

# %%
from mlflow.tracking import MlflowClient

try:
    client = MlflowClient()
    registered_models = client.search_registered_models()
    
    if not registered_models:
        print("ℹ️ No models registered in registry yet.")
    else:
        model_data = []
        for model in registered_models:
            for version in model.latest_versions:
                model_data.append({
                    "Model Name": model.name,
                    "Version": f"v{version.version}",
                    "Stage": version.current_stage,
                    "Run ID": version.run_id,
                    "Source URI": version.source,
                    "Last Updated": pd.to_datetime(version.last_updated_timestamp, unit='ms').strftime('%Y-%m-%d %H:%M:%S')
                })
        
        if model_data:
            model_df = pd.DataFrame(model_data)
            display(HTML(model_df.to_html(classes='dataframe', index=False)))
        else:
            print("ℹ️ Models exist, but no active versions are registered.")
except Exception as e:
    print(f"⚠️ Error loading Model Registry: {e}")

# %% [markdown]
# ## 🗄️ DVC Data Tracking Status
#
# Checking workspace status and listing tracked assets:

# %%
import subprocess
import glob

# Query DVC status
try:
    result = subprocess.run(["dvc", "status"], capture_output=True, text=True, check=True)
    if "No changes" in result.stdout or not result.stdout.strip():
        print("✅ DVC workspace is clean. All tracked data artifacts are up to date.")
    else:
        print("⚠️ DVC workspace has modified or untracked changes:")
        print(result.stdout)
except Exception as e:
    print(f"⚠️ Could not execute dvc status: {e}")

# %%
# Locate and parse all .dvc files to show what assets are tracked
dvc_files = glob.glob("**/*.dvc", recursive=True)
if not dvc_files:
    print("ℹ️ No `.dvc` tracking metadata files found in this workspace.")
else:
    dvc_data = []
    for f in dvc_files:
        try:
            with open(f, 'r') as file:
                lines = file.readlines()
                outs_section = False
                md5 = ""
                path = ""
                for line in lines:
                    if "outs:" in line:
                        outs_section = True
                    if outs_section:
                        if "md5:" in line:
                            md5 = line.split("md5:")[-1].strip()
                        if "path:" in line:
                            path = line.split("path:")[-1].strip()
                dvc_data.append({
                    "DVC File": f,
                    "Tracked Asset": path if path else "N/A",
                    "Content Hash (MD5)": md5 if md5 else "N/A"
                })
        except Exception:
            pass
            
    if dvc_data:
        dvc_df = pd.DataFrame(dvc_data)
        display(HTML(dvc_df.to_html(classes='dataframe', index=False)))
